package com.pochak.content.highlight.repository;

import com.pochak.content.highlight.entity.Highlight;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HighlightRepository extends JpaRepository<Highlight, Long> {

    List<Highlight> findByContentIdAndContentTypeOrderByStartTimeSecondsAsc(Long contentId, String contentType);

    void deleteByContentIdAndContentTypeAndIsAutoGeneratedTrue(Long contentId, String contentType);
}
