import apiClient from '../api/client';

// ─── Types ───────────────────────────────────────────────────────

export type HighlightType = 'GOAL' | 'SAVE' | 'FOUL' | 'RALLY' | 'DUNK' | 'ACE' | 'CUSTOM';

export interface Highlight {
  id: number;
  contentId: number;
  contentType: string;
  startTimeSeconds: number;
  endTimeSeconds: number;
  highlightType: HighlightType;
  confidenceScore: number;
  description: string;
  isAutoGenerated: boolean;
  createdAt: string;
}

// ─── Highlight type labels (Korean) ─────────────────────────────

export const HIGHLIGHT_TYPE_LABELS: Record<HighlightType, string> = {
  GOAL: '골',
  SAVE: '세이브',
  FOUL: '파울',
  RALLY: '랠리',
  DUNK: '덩크',
  ACE: '에이스',
  CUSTOM: '커스텀',
};

export const HIGHLIGHT_TYPE_COLORS: Record<HighlightType, string> = {
  GOAL: '#4CAF50',
  SAVE: '#2196F3',
  FOUL: '#FFD600',
  RALLY: '#FF9800',
  DUNK: '#E91E63',
  ACE: '#9C27B0',
  CUSTOM: '#FFFFFF',
};

// ─── Mock data ──────────────────────────────────────────────────

function generateMockHighlights(contentType: string, contentId: string): Highlight[] {
  const types: HighlightType[] = ['GOAL', 'SAVE', 'FOUL', 'GOAL', 'SAVE', 'FOUL'];
  const descriptions = [
    '결정적 순간 - 골 장면',
    '수비 하이라이트 - 슈퍼 세이브',
    '파울 장면',
    '역전 골 장면',
    '놀라운 세이브',
    '반칙 판정 장면',
  ];

  const count = 4 + Math.floor(Math.random() * 3); // 4-6
  const duration = 7200;
  const interval = Math.floor(duration / (count + 1));

  return Array.from({length: count}, (_, i) => {
    const startSec = interval * (i + 1) + Math.floor(Math.random() * 60);
    return {
      id: i + 1,
      contentId: Number(contentId) || i + 100,
      contentType: contentType.toUpperCase(),
      startTimeSeconds: startSec,
      endTimeSeconds: startSec + 10 + Math.floor(Math.random() * 15),
      highlightType: types[i % types.length],
      confidenceScore: 0.7 + Math.random() * 0.3,
      description: descriptions[i % descriptions.length],
      isAutoGenerated: true,
      createdAt: new Date().toISOString(),
    };
  });
}

// ─── API functions ──────────────────────────────────────────────

/**
 * Fetch highlights for a content item.
 * API-first with mock fallback during development.
 */
export async function getHighlights(
  contentType: string,
  contentId: string,
): Promise<Highlight[]> {
  try {
    const response = await apiClient.get(
      `/contents/${contentType}/${contentId}/highlights`,
    );
    const data = response.data?.data ?? response.data;
    if (Array.isArray(data) && data.length > 0) {
      return data;
    }
    // If API returns empty, fall back to mock
    return generateMockHighlights(contentType, contentId);
  } catch {
    // API not available yet — return mock data
    return generateMockHighlights(contentType, contentId);
  }
}

/**
 * Trigger auto-detection of highlights (stub).
 */
export async function detectHighlights(
  contentType: string,
  contentId: string,
): Promise<{highlights: Highlight[]; generatedClipIds: number[]}> {
  try {
    const response = await apiClient.post(
      `/contents/${contentType}/${contentId}/highlights/detect`,
    );
    return response.data?.data ?? response.data;
  } catch {
    return {
      highlights: generateMockHighlights(contentType, contentId),
      generatedClipIds: [],
    };
  }
}

/**
 * Create a manual highlight.
 */
export async function createManualHighlight(
  contentType: string,
  contentId: string,
  params: {
    startTimeSeconds: number;
    endTimeSeconds: number;
    highlightType: string;
    description?: string;
  },
): Promise<Highlight> {
  const response = await apiClient.post(
    `/contents/${contentType}/${contentId}/highlights`,
    params,
  );
  return response.data?.data ?? response.data;
}
