package com.pochak.content.highlight.dto;

import com.pochak.content.highlight.entity.Highlight;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class HighlightResponse {

    private Long id;
    private Long contentId;
    private String contentType;
    private Integer startTimeSeconds;
    private Integer endTimeSeconds;
    private String highlightType;
    private Double confidenceScore;
    private String description;
    private Boolean isAutoGenerated;
    private LocalDateTime createdAt;

    public static HighlightResponse from(Highlight highlight) {
        return HighlightResponse.builder()
                .id(highlight.getId())
                .contentId(highlight.getContentId())
                .contentType(highlight.getContentType())
                .startTimeSeconds(highlight.getStartTimeSeconds())
                .endTimeSeconds(highlight.getEndTimeSeconds())
                .highlightType(highlight.getHighlightType().name())
                .confidenceScore(highlight.getConfidenceScore())
                .description(highlight.getDescription())
                .isAutoGenerated(highlight.getIsAutoGenerated())
                .createdAt(highlight.getCreatedAt())
                .build();
    }
}
