name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      KAKAO_REST_KEY: ${{ secrets.KAKAO_REST_KEY }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      THINGPLUG_UKEY: ${{ secrets.THINGPLUG_UKEY }}

    steps:

    - name: Note Build Start Time
      id : start_time
      run : echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: 1️⃣ Checkout Repository
      uses: actions/checkout@v3

    - name: 2️⃣ Decode & Restore Service Account Key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > blinker-backend-key.json
        ls -l blinker-backend-key.json

    - name: 3️⃣ Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: 4️⃣ Configure Docker Authentication
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: 5️⃣ Build Docker Image
      run: docker build -t asia-northeast3-docker.pkg.dev/blinker-backend1/blinker-repo/blinker-backend1:latest .

    - name: 6️⃣ Push Docker Image to Artifact Registry
      run: docker push asia-northeast3-docker.pkg.dev/blinker-backend1/blinker-repo/blinker-backend1:latest

    - name: 7️⃣ Deploy to Cloud Run
      run: |
        gcloud run deploy blinker-backend1 \
          --image=asia-northeast3-docker.pkg.dev/blinker-backend1/blinker-repo/blinker-backend1:latest \
          --platform=managed \
          --vpc-connector=my-connector \
          --vpc-egress=all-traffic \
          --region=asia-northeast3 \
          --allow-unauthenticated \
          --add-cloudsql-instances=blinker-db:asia-northeast3:blinker-atom-db \
          --set-env-vars "SPRING_PROFILES_ACTIVE=prod,THINGPLUG_URL=http://thingplugpf.sktiot.com:9000,GOOGLE_APPLICATION_CREDENTIALS=/app/blinker-backend-key.json,THINGPLUG_UKEY=${{ secrets.THINGPLUG_UKEY }},JWT_SECRET=${{ secrets.JWT_SECRET }},KAKAO_REST_KEY=${{ secrets.KAKAO_REST_KEY }},DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}"


    - name: 종료 시간 기록
      id: end_time
      run: |
        echo "END_TIME=$(date +%s)" >> $GITHUB_ENV
        echo "BUILD_TIME=$(( $(date +%s) - $START_TIME ))" >> $GITHUB_ENV
      

    - name : 배포 실패 시 종료 시간 기록
      if: failure()
      run : |
          echo "END_TIME=$(date +%s)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(( $(date +%s) - $START_TIME ))" >> $GITHUB_ENV

    - name: 빌드 실패 Discord 알림
      if: failure()
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: "🌋 **배포 실패.**"
        embed-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: |
          𝑒 **배포 환경:** `prod`
          𝘣 **대상 브랜치:** `${{ github.ref_name }}`
          𝑡 **소요 시간:** `${{ env.BUILD_TIME }}초`
          𝒈 **액션 링크:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        embed-color: "16711680"

    - name: 빌드 성공 Discord 알림
      if: success()
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: "✅ **배포 성공.**"
        embed-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        embed-description: |
          𝑒 **배포 환경:** `prod`
          𝘣 **대상 브랜치:** `${{ github.ref_name }}`
          𝑡 **소요 시간:** `${{ env.BUILD_TIME }}초`
          𝒈 **액션 링크:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        embed-color: "3066993"
