package com.pochak.content.highlight.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "highlights", schema = "content")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class Highlight {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "content_id", nullable = false)
    private Long contentId;

    @Column(name = "content_type", nullable = false, length = 10)
    private String contentType;

    @Column(name = "start_time_seconds", nullable = false)
    private Integer startTimeSeconds;

    @Column(name = "end_time_seconds", nullable = false)
    private Integer endTimeSeconds;

    @Enumerated(EnumType.STRING)
    @Column(name = "highlight_type", nullable = false, length = 30)
    private HighlightType highlightType;

    @Column(name = "confidence_score", precision = 3)
    private Double confidenceScore;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "is_auto_generated", nullable = false)
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    public enum HighlightType {
        GOAL, SAVE, FOUL, RALLY, DUNK, ACE, CUSTOM
    }
}
