#!/usr/bin/env node
/**
 * Runner auto-setup script.
 * Usage: npx ts-node src/setup.ts <RUNNER_API_TOKEN> [CLOUD_API_URL]
 *
 * 1. Calls GET /runner/me with the token to fetch runner/tenant info
 * 2. Writes .env file automatically
 * 3. Prints success message
 */
import * as fs from 'fs';
import * as path from 'path';

const token = process.argv[2];
const cloudUrl = process.argv[3] || 'http://localhost:4000/api/v1';

if (!token) {
  console.error('Usage: npm run runner:setup -- <RUNNER_API_TOKEN> [CLOUD_API_URL]');
  console.error('');
  console.error('  RUNNER_API_TOKEN  The ktr_... token from the Cloud Dashboard');
  console.error('  CLOUD_API_URL     (optional) defaults to http://localhost:4000/api/v1');
  process.exit(1);
}

async function main() {
  console.log('Connecting to Cloud API...');
  console.log(`  URL: ${cloudUrl}`);

  const res = await fetch(`${cloudUrl}/runner/me`, {
    headers: { 'X-Runner-Token': token },
  });

  if (!res.ok) {
    const text = await res.text();
    console.error(`Failed to validate token: ${res.status} ${text}`);
    process.exit(1);
  }

  const info = await res.json() as { runnerName: string; runnerId: string; tenantName: string; tenantId: string };
  console.log(`  Runner: ${info.runnerName} (${info.runnerId})`);
  console.log(`  Tenant: ${info.tenantName} (${info.tenantId})`);

  const envContent = [
    `# Auto-generated by runner:setup`,
    `# Runner: ${info.runnerName}`,
    `# Tenant: ${info.tenantName}`,
    ``,
    `TENANT_ID=${info.tenantId}`,
    `RUNNER_ID=${info.runnerId}`,
    `RUNNER_API_TOKEN=${token}`,
    `CLOUD_API_URL=${cloudUrl}`,
    ``,
    `REDIS_HOST=localhost`,
    `REDIS_PORT=6379`,
    `RUNNER_PLATFORMS=web`,
    `LOCAL_API_PORT=5001`,
    ``,
  ].join('\n');

  const envPath = path.resolve(__dirname, '../.env');
  fs.writeFileSync(envPath, envContent);
  console.log(`\n.env written to ${envPath}`);
  console.log('\nSetup complete! Start the runner with:');
  console.log('  npm run runner:dev');
}

main().catch((e) => {
  console.error('Setup failed:', e.message);
  process.exit(1);
});
