package com.pochak.content.highlight.service;

import com.pochak.content.highlight.dto.CreateHighlightRequest;
import com.pochak.content.highlight.dto.HighlightResponse;
import com.pochak.content.highlight.entity.Highlight;
import com.pochak.content.highlight.entity.Highlight.HighlightType;
import com.pochak.content.highlight.repository.HighlightRepository;
import com.pochak.content.asset.entity.LiveAsset;
import com.pochak.content.asset.entity.VodAsset;
import com.pochak.content.asset.repository.LiveAssetRepository;
import com.pochak.content.asset.repository.VodAssetRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class HighlightService {

    private final HighlightRepository highlightRepository;
    private final VodAssetRepository vodAssetRepository;
    private final LiveAssetRepository liveAssetRepository;

    private static final Random RANDOM = new Random();

    /**
     * Stub: auto-detect highlights for a content item.
     * In production, this would call an AI inference service.
     * Currently generates mock highlights spread across the content duration.
     */
    @Transactional
    public List<HighlightResponse> detectHighlights(Long contentId, String contentType) {
        log.info("Detecting highlights for content {} (type={})", contentId, contentType);

        // 멱등성 보장: 기존 자동 생성 하이라이트 삭제 후 재생성
        highlightRepository.deleteByContentIdAndContentTypeAndIsAutoGeneratedTrue(
                contentId, contentType.toUpperCase());

        // Determine content duration; fall back to a default if not found.
        int durationSeconds = resolveContentDuration(contentId, contentType);

        // Resolve sport code and select sport-specific highlight types/descriptions
        String sportCode = resolveSportCode(contentId, contentType);
        HighlightType[] candidateTypes;
        String[] descriptions;

        switch (sportCode) {
            case "SOCCER" -> {
                candidateTypes = new HighlightType[]{
                        HighlightType.GOAL, HighlightType.SAVE, HighlightType.FOUL, HighlightType.FREE_KICK
                };
                descriptions = new String[]{
                        "골 장면 - 결정적 순간", "슈퍼 세이브 - 수비 하이라이트",
                        "파울 장면", "프리킥 득점 장면", "역전 골", "헤더 골"
                };
            }
            case "BASKETBALL" -> {
                candidateTypes = new HighlightType[]{
                        HighlightType.DUNK, HighlightType.THREE_POINTER, HighlightType.BLOCK
                };
                descriptions = new String[]{
                        "덩크슛 장면", "3점슛 성공", "블록슛 - 수비 하이라이트",
                        "역전 3점슛", "앨리웁 덩크"
                };
            }
            case "BASEBALL" -> {
                candidateTypes = new HighlightType[]{
                        HighlightType.HOME_RUN, HighlightType.STRIKEOUT, HighlightType.DOUBLE_PLAY
                };
                descriptions = new String[]{
                        "홈런 장면", "삼진 아웃", "병살타 - 수비 하이라이트",
                        "만루 홈런", "끝내기 홈런"
                };
            }
            case "VOLLEYBALL" -> {
                candidateTypes = new HighlightType[]{
                        HighlightType.ACE, HighlightType.RALLY, HighlightType.BLOCK
                };
                descriptions = new String[]{
                        "에이스 서브 득점", "장기 랠리 하이라이트", "블로킹 성공",
                        "다이빙 리시브", "강스파이크 득점"
                };
            }
            default -> {
                candidateTypes = new HighlightType[]{
                        HighlightType.GOAL, HighlightType.SAVE, HighlightType.FOUL,
                        HighlightType.RALLY, HighlightType.DUNK, HighlightType.ACE
                };
                descriptions = new String[]{
                        "결정적 순간", "수비 하이라이트", "파울 장면",
                        "랠리 하이라이트", "덩크슛 장면", "에이스 포인트"
                };
            }
        }

        int highlightCount = 4 + RANDOM.nextInt(5); // 4-8
        int interval = Math.max(durationSeconds / (highlightCount + 1), 30);

        List<Highlight> generated = new ArrayList<>();
        for (int i = 0; i < highlightCount; i++) {
            int startSec = interval * (i + 1) + RANDOM.nextInt(Math.max(interval / 4, 1));
            startSec = Math.min(startSec, durationSeconds - 10);
            int endSec = Math.min(startSec + 10 + RANDOM.nextInt(20), durationSeconds);

            HighlightType type = candidateTypes[RANDOM.nextInt(candidateTypes.length)];
            double confidence = 0.6 + RANDOM.nextDouble() * 0.4; // 0.6-1.0
            confidence = Math.round(confidence * 100.0) / 100.0;

            Highlight highlight = Highlight.builder()
                    .contentId(contentId)
                    .contentType(contentType.toUpperCase())
                    .startTimeSeconds(startSec)
                    .endTimeSeconds(endSec)
                    .highlightType(type)
                    .confidenceScore(confidence)
                    .description(descriptions[RANDOM.nextInt(descriptions.length)])
                    .isAutoGenerated(true)
                    .build();

            generated.add(highlight);
        }

        List<Highlight> saved = highlightRepository.saveAll(generated);
        log.info("Generated {} mock highlights for content {}", saved.size(), contentId);

        return saved.stream()
                .map(HighlightResponse::from)
                .collect(Collectors.toList());
    }

    /**
     * Get highlights for a content item, sorted by start time.
     */
    @Transactional(readOnly = true)
    public List<HighlightResponse> getHighlights(Long contentId, String contentType) {
        List<Highlight> highlights = highlightRepository
                .findByContentIdAndContentTypeOrderByStartTimeSecondsAsc(contentId, contentType.toUpperCase());

        return highlights.stream()
                .map(HighlightResponse::from)
                .collect(Collectors.toList());
    }

    /**
     * Create a manual highlight (by user or admin).
     */
    @Transactional
    public HighlightResponse createManualHighlight(Long contentId, String contentType,
                                                    CreateHighlightRequest request) {
        HighlightType type;
        try {
            type = HighlightType.valueOf(request.getHighlightType().toUpperCase());
        } catch (IllegalArgumentException e) {
            type = HighlightType.CUSTOM;
        }

        Highlight highlight = Highlight.builder()
                .contentId(contentId)
                .contentType(contentType.toUpperCase())
                .startTimeSeconds(request.getStartTimeSeconds())
                .endTimeSeconds(request.getEndTimeSeconds())
                .highlightType(type)
                .confidenceScore(1.0) // manual = full confidence
                .description(request.getDescription())
                .isAutoGenerated(false)
                .build();

        Highlight saved = highlightRepository.save(highlight);
        return HighlightResponse.from(saved);
    }

    private int resolveContentDuration(Long contentId, String contentType) {
        if ("VOD".equalsIgnoreCase(contentType)) {
            return vodAssetRepository.findByIdAndDeletedAtIsNull(contentId)
                    .map(VodAsset::getDuration)
                    .orElse(7200); // default 2 hours
        }
        // For LIVE or CLIP, use reasonable defaults
        return 3600;
    }

    private String resolveSportCode(Long contentId, String contentType) {
        try {
            if ("VOD".equalsIgnoreCase(contentType)) {
                return vodAssetRepository.findByIdAndDeletedAtIsNull(contentId)
                        .map(VodAsset::getMatch)
                        .filter(m -> m != null && m.getSport() != null)
                        .map(m -> m.getSport().getCode())
                        .orElse("UNKNOWN");
            } else if ("LIVE".equalsIgnoreCase(contentType)) {
                return liveAssetRepository.findByIdAndDeletedAtIsNull(contentId)
                        .map(LiveAsset::getMatch)
                        .filter(m -> m != null && m.getSport() != null)
                        .map(m -> m.getSport().getCode())
                        .orElse("UNKNOWN");
            }
        } catch (Exception e) {
            log.warn("Failed to resolve sport code for content {} ({}): {}", contentId, contentType, e.getMessage());
        }
        return "UNKNOWN";
    }
}
